SHELL := /bin/bash
PY ?= .venv/bin/python
PORT ?= 8080

# Packages written into the curated lock. Keep in sync with requirements.txt.
LOCK_PKGS := opencv-contrib-python|numpy|fastapi|uvicorn|httpx|python-multipart|jinja2|boto3

.PHONY: help venv dev install lock run api eval evidence test lint typecheck fmt docker lambda-package clean

help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

venv: ## Create the virtual environment
	python3 -m venv --system-site-packages .venv
	$(PY) -m pip install --upgrade pip

dev: ## Install the project with dev extras (pytest, ruff, mypy)
	@test -x $(PY) || { echo "no .venv — run 'make venv' first"; exit 1; }
	$(PY) -m pip install -e ".[dev]"

install: ## Install runtime + dev dependencies
	$(PY) -m pip install -r requirements.txt -e ".[dev]"

lock: ## Regenerate the curated exact-pin lock from requirements.txt
	@test -x $(PY) || { echo "no .venv — run 'make venv' first"; exit 1; }
	@{ \
	  echo "# Curated exact pins for Argus' direct runtime dependencies."; \
	  echo "# Generated by 'make lock' from requirements.txt, which is the single"; \
	  echo "# source of truth for versions. Edit requirements.txt, then re-run 'make lock'."; \
	  grep -iE '^($(LOCK_PKGS))==' requirements.txt | sort -f; \
	} > requirements.lock
	@echo "wrote requirements.lock ($$(grep -c '^[^#]' requirements.lock) pinned packages)"

api: ## Run the web endpoint
	$(PY) -m uvicorn argus.api:app --host 0.0.0.0 --port $(PORT)

eval: ## Run the evaluation harness
	$(PY) -m argus.eval --clips 12 --out var/eval

evidence: eval ## Regenerate judge-accessible evidence under docs/evidence
	mkdir -p docs/evidence
	cp var/eval/metrics.json var/eval/summary.json var/eval/rows.json docs/evidence/
	cp var/eval/runs/decisions.jsonl docs/evidence/decisions.jsonl

test: ## Run the test suite
	$(PY) -m pytest

lint: ## Static checks (ruff + mypy) — fails on any finding
	@test -x $(PY) || { echo "no .venv — run 'make venv' first"; exit 1; }
	@$(PY) -c "import ruff" 2>/dev/null \
	  || { echo "ruff is not installed — run 'make dev'"; exit 1; }
	@$(PY) -c "import mypy" 2>/dev/null \
	  || { echo "mypy is not installed — run 'make dev'"; exit 1; }
	$(PY) -m ruff check src tests
	$(PY) -m mypy src

typecheck: ## Type-check only
	@test -x $(PY) || { echo "no .venv — run 'make venv' first"; exit 1; }
	@$(PY) -c "import mypy" 2>/dev/null \
	  || { echo "mypy is not installed — run 'make dev'"; exit 1; }
	$(PY) -m mypy src

fmt: ## Auto-format with ruff
	@$(PY) -c "import ruff" 2>/dev/null \
	  || { echo "ruff is not installed — run 'make dev'"; exit 1; }
	$(PY) -m ruff format src tests

docker: ## Build the container image
	docker build -t argus-triage:0.1.0 .

# The S3-triggered triage handler, packaged for `terraform apply` in
# infra/terraform. The zip must exist before the plan; see infra/terraform/README.md.
lambda-package: ## Build infra/terraform/build/argus-lambda.zip for the triage Lambda
	bash infra/terraform/build-lambda.sh

clean: ## Remove generated artefacts
	rm -rf var .pytest_cache .ruff_cache .mypy_cache build dist *.egg-info
	find . -name __pycache__ -type d -prune -exec rm -rf {} +
